name: "run-tests"
on:
  push:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0

    # use docker to get around the lack for TTY for fzf and mpv
    - run: ./run-tests
